db:
    image: "mysql"
    environment:
        MYSQL_ROOT_PASSWORD: mysecretpassword
experimenthub:
    environment:
        MYSQL_ROOT_PASSWORD: mysecretpassword
        MYSQL_REMOTE_PASSWORD: 
    image: "bioconductor/experimenthub_docker"
    links:
     - "db"
    ports:
     - "3000:3000"
    volumes:
     - "./HubServer:/HubServer"
     - "./data:/data"
    command:  "/tmp/start.sh"

