db:
    image: "mysql:8.0.19"
    environment:
        MYSQL_ROOT_PASSWORD: mysecretpassword
experimenthub:
    environment:
        MYSQL_ROOT_PASSWORD: mysecretpassword
        MYSQL_REMOTE_PASSWORD: 
    image: "bioconductor/experimenthub_docker"
    links:
     - "db"
    ports:
     - "4000:3000"
    volumes:
     - "./HubServer:/HubServer"
     - "./data:/data"
    command:  "/bin/bash --login /tmp/start.sh"

